# Generated by Django 5.2.3 on 2025-06-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
